version: 0.0
os: linux

files:
  - source: /

hooks:
  ApplicationStop:
    - location: simple-python-app/scripts/stop_container.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: simple-python-app/scripts/stop_container.sh
      timeout: 300
      runas: root